spring:
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 数据库
      # url: jdbc:postgresql://10.80.0.110:5432/sca_cloud
      # username: postgres
      # password: BM8nw7l9mmMG1ru
      # driver-class-name: org.postgresql.Driver
      # 连接池-初始化大小
      initial-size: 10
      # 连接池-最大连接数
      max-active: 100
      # 最大等待时间
      max-wait: 60000
      # 连接池-最小空闲数
      min-idle: 10
      # 检测空闲连接
      test-while-idle: true
      # 最小空闲时间
      min-evictable-idle-time-millis: 300000
  # redis
  data:
    redis:
      # port: 6379
      # host: 10.80.0.110
      # password: Jb6xMAm6CWQ6zsX
      # database: 2
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数（使用Lettuce时）
          max-wait: -1ms # 连接池最大阻塞等待时间（使用Lettuce时）
          max-idle: 8 # 连接池中的最大空闲连接（使用Lettuce时）
          min-idle: 0 # 连接池中的最小空闲连接（使用Lettuce时）

  #国际化配置
  messages:
    basename: i18n.messages
    encoding: UTF-8

